Notes Manager/Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Notes_Manager.Data;
using Notes_Manager.Models;

namespace Notes_Manager.Controllers
{
    [Authorize]
    public class NotesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public NotesController(ApplicationDbContext context, UserManager<ApplicationUser> usermanager)
        {
            _userManager = usermanager;
            _context = context;
        }

        // GET: Notes
        public async Task<IActionResult> Index(string SearchString, string Category)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            ViewData["CategoryName"] = new SelectList(_context.Category.Where(x => x.UserId == user.Id), "Name", "Name");
            if (!string.IsNullOrEmpty(Category) && Category!="Wszystkie")
            {
                var applicationDbContext = _context.Notes.Include(n => n.Category).Include(n => n.user).Where(x => x.UserId == user.Id && x.Category.Name == Category);
                return View(await applicationDbContext.ToListAsync());
            }
            if (!string.IsNullOrEmpty(SearchString))
            {
                var applicationDbContext = _context.Notes.Include(n => n.Category).Include(n => n.user).Where(x => x.UserId == user.Id && x.Title.Contains(SearchString) || x.Content.Contains(SearchString) || x.Category.Name.Contains(SearchString));
                return View(await applicationDbContext.ToListAsync());
            }
            else
            {
                var applicationDbContext = _context.Notes.Include(n => n.Category).Include(n => n.user).Where(x => x.UserId == user.Id);
                return View(await applicationDbContext.ToListAsync());
            }
        }

        // GET: Notes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Notes == null)
            {
                return NotFound();
            }

            var notes = await _context.Notes
                .Include(n => n.Category)
                .Include(n => n.user)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (notes == null)
            {
                return NotFound();
            }

            return View(notes);
        }

        // GET: Notes/Create
        public async Task<IActionResult> Create()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            ViewData["CategoryId"] = new SelectList(_context.Category.Where(x => x.UserId == user.Id), "Id", "Name");
            return View();
        }

        // POST: Notes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Content,CategoryId")] Notes notes)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            notes.UserId = user.Id;
            //if (ModelState.IsValid)
           // {
                _context.Add(notes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
           // }
            ViewData["CategoryId"] = new SelectList(_context.Category, "Id", "Id", notes.CategoryId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", notes.UserId);
            return View(notes);
        }

        // GET: Notes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Notes == null)
            {
                return NotFound();
            }

            var notes = await _context.Notes.FindAsync(id);
            if (notes == null)
            {
                return NotFound();
            }
            var user = await _userManager.GetUserAsync(HttpContext.User);
            ViewData["CategoryId"] = new SelectList(_context.Category.Where(x => x.UserId == user.Id), "Id", "Name", notes.CategoryId);
            return View(notes);
        }

        // POST: Notes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Content,CategoryId")] Notes notes)
        {
            if (id != notes.Id)
            {
                return NotFound();
            }

            //if (ModelState.IsValid)
            //{
            var user = await _userManager.GetUserAsync(HttpContext.User);
            notes.UserId = user.Id;
            try
                {
                    _context.Update(notes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NotesExists(notes.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            //}
            ViewData["CategoryId"] = new SelectList(_context.Category, "Id", "Id", notes.CategoryId);
            return View(notes);
        }

        // GET: Notes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Notes == null)
            {
                return NotFound();
            }

            var notes = await _context.Notes
                .Include(n => n.Category)
                .Include(n => n.user)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (notes == null)
            {
                return NotFound();
            }

            return View(notes);
        }

        // POST: Notes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Notes == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Notes'  is null.");
            }
            var notes = await _context.Notes.FindAsync(id);
            if (notes != null)
            {
                _context.Notes.Remove(notes);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NotesExists(int id)
        {
          return _context.Notes.Any(e => e.Id == id);
        }


    }
}

Notes Manager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Notes_Manager</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Notes_Manager.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="page-content container">
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light mb-3">
                <div class="container-fluid p-0">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Manager Notatek</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Notes" asp-action="Create">Utwórz notatke</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Notes" asp-action="Index">Przeglądaj</a>
                            </li>
                        </ul>
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </nav>
        </header>

        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>